name: Package hugegraph-computer image

on:
  workflow_dispatch:
    inputs:
      repository_branch:
        required: true
        default: 'master'
      framework_image_url:
        required: true
        default: 'hugegraph-computer:0.1.0'
      algorithm_image_url:
        required: true
        default: 'hugegraph-computer-algorithm:0.1.0'
      operator_image_url:
        required: true
        default: 'hugegraph-computer-operator:0.1.0'
      release_tag:
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - run: docker version

      - name: Install JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.repository_branch }}
          fetch-depth: 2

      - name: Replace jar
        env:
          TRAVIS_DIR: computer-dist/src/assembly/travis
        run: |
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hugegraph-client-3.5.0.jar -DgroupId=com.baidu.hugegraph -DartifactId=hugegraph-client -Dversion=3.5.0 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/lib/hugegraph-client-3.5.0.pom
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hugegraph-common-1.8.10.jar -DgroupId=com.baidu.hugegraph -DartifactId=hugegraph-common -Dversion=1.8.10 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/lib/hugegraph-common-1.8.10.pom
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hugegraph-core-3.5.0.jar -DgroupId=com.baidu.hugegraph -DartifactId=hugegraph-core -Dversion=3.5.0 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/lib/hugegraph-core-3.5.0.pom
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hugegraph-hstore-3.5.0.jar -DgroupId=com.baidu.hugegraph -DartifactId=hugegraph-hstore -Dversion=3.5.0 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/lib/hugegraph-hstore-3.5.0.pom
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hugegraph.pom -DgroupId=com.baidu.hugegraph -DartifactId=hugegraph -Dversion=3.5.0 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/lib/hugegraph.pom
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hugegraph-pd-root-3.5.0.pom -DgroupId=com.baidu.hugegraph -DartifactId=hugegraph-pd-root -Dversion=3.5.0 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/lib/hugegraph-pd-root-3.5.0.pom
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hugegraph-loader-3.5.0.jar -DgroupId=com.baidu.hugegraph -DartifactId=hugegraph-loader -Dversion=3.5.0 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/lib/hugegraph-loader-3.5.0.pom
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hugegraph-plugin-3.5.0.jar -DgroupId=com.baidu.hugegraph -DartifactId=hugegraph-plugin -Dversion=3.5.0 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/lib/hugegraph-plugin-3.5.0.pom
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/syncgateway-1.0.0.jar -DgroupId=com.baidu.hugegraph -DartifactId=syncgateway -Dversion=1.0.0 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/lib/syncgateway-pom.xml
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hg-pd-client-3.5.0.jar -DgroupId=com.baidu.hugegraph -DartifactId=hg-pd-client -Dversion=3.5.0 -Dpackaging=jar  -DpomFile=$TRAVIS_DIR/lib/hg-pd-client-3.5.0.pom
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hg-pd-common-3.5.0.jar -DgroupId=com.baidu.hugegraph -DartifactId=hg-pd-common -Dversion=3.5.0 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/lib/hg-pd-common-3.5.0.pom
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hg-pd-grpc-3.5.0.jar -DgroupId=com.baidu.hugegraph -DartifactId=hg-pd-grpc -Dversion=3.5.0 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/lib/hg-pd-grpc-3.5.0.pom
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hg-store-client-3.5.0.jar -DgroupId=com.baidu.hugegraph -DartifactId=hg-store-client -Dversion=3.5.0 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/lib/hg-store-client-3.5.0.pom
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hg-store-grpc-3.5.0.jar -DgroupId=com.baidu.hugegraph -DartifactId=hg-store-grpc -Dversion=3.5.0 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/lib/hg-store-grpc-3.5.0.pom
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hg-store-common-3.5.0.jar -DgroupId=com.baidu.hugegraph -DartifactId=hg-store-common -Dversion=3.5.0 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/lib/hg-store-common-3.5.0.pom
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hadoop/hadoop-annotations-2.7.2.jar -DgroupId=org.apache.hadoop -DartifactId=hadoop-annotations -Dversion=2.7.2 -Dpackaging=jar
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hadoop/hadoop-auth-2.7.2.jar -DgroupId=org.apache.hadoop -DartifactId=hadoop-auth -Dversion=2.7.2 -Dpackaging=jar
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hadoop/hadoop-client-2.7.2.jar -DgroupId=org.apache.hadoop -DartifactId=hadoop-client -Dversion=2.7.2 -Dpackaging=jar
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hadoop/hadoop-common-2.7.2.jar -DgroupId=org.apache.hadoop -DartifactId=hadoop-common -Dversion=2.7.2 -Dpackaging=jar
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hadoop/hadoop-hdfs-2.7.2.jar -DgroupId=org.apache.hadoop -DartifactId=hadoop-hdfs -Dversion=2.7.2 -Dpackaging=jar
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hadoop/hadoop-hdfs-client-2.7.2.jar -DgroupId=org.apache.hadoop -DartifactId=hadoop-hdfs-client -Dversion=2.7.2 -Dpackaging=jar

      - name: Build images
        env:
          TRAVIS_DIR: computer-dist/src/assembly/travis
        run: $TRAVIS_DIR/build-images-gh.sh ${{ github.event.inputs.framework_image_url }} ${{ github.event.inputs.algorithm_image_url }} ${{ github.event.inputs.operator_image_url }} -Dhadoop-version=2.7.2

      - name: Docker images
        run: docker images

      - name: Save image
        run: |
          mkdir artifacts
          chmod -R 777 ./artifacts
          docker save -o ./artifacts/hugegraph-computer-framework.tar ${{ github.event.inputs.framework_image_url }}
          docker save -o ./artifacts/hugegraph-computer-algorithm.tar ${{ github.event.inputs.algorithm_image_url }}
          docker save -o ./artifacts/hugegraph-computer-operator.tar ${{ github.event.inputs.operator_image_url }}

      - name: Upload github release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "./artifacts/*"
          tags: true
          draft: false
          overwrite: true
          tag_name: ${{ github.event.inputs.release_tag }}
