name: Package hugegraph-computer image

on:
  workflow_dispatch:
    inputs:
      repository_branch:
        required: true
        default: 'master'
      framework_image_url:
        required: true
        default: 'hugegraph-computer:0.1.0'
      algorithm_image_url:
        required: true
        default: 'hugegraph-computer-algorithm:0.1.0'
      operator_image_url:
        required: true
        default: 'hugegraph-computer-operator:0.1.0'
      release_tag:
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - run: docker version

      - name: Install JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.repository_branch }}
          fetch-depth: 2

      - name: Replace jar
        env:
          TRAVIS_DIR: computer-dist/src/assembly/travis
        run: |
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hugegraph-client-3.0.0.jar -DgroupId=com.baidu.hugegraph -DartifactId=hugegraph-client -Dversion=3.0.0 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/lib/client-pom.xml
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hugegraph-common-1.8.10.jar -DgroupId=com.baidu.hugegraph -DartifactId=hugegraph-common -Dversion=1.8.10 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/lib/common-pom.xml
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hugegraph-core-3.0.0.jar -DgroupId=com.baidu.hugegraph -DartifactId=hugegraph-core -Dversion=3.0.0 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/lib/hugegraph-core-pom.xml
          mvn install:install-file -Dfile=$TRAVIS_DIR/lib/hugegraph-loader-0.11.3.jar -DgroupId=com.baidu.hugegraph -DartifactId=hugegraph-loader -Dversion=0.11.3 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/lib/hugegraph-loader-0.11.3-pom.xml
          mvn install:install-file -Dfile=$TRAVIS_DIR/hg-pd-client-3.0.0.jar -DgroupId=com.baidu.hugegraph -DartifactId=hg-pd-client -Dversion=3.0.0 -Dpackaging=jar  -DpomFile=$TRAVIS_DIR/hg-pd-client-pom.xml
          mvn install:install-file -Dfile=$TRAVIS_DIR/hg-pd-common-3.0.0.jar -DgroupId=com.baidu.hugegraph -DartifactId=hg-pd-common -Dversion=3.0.0 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/hg-pd-common-pom.xml
          mvn install:install-file -Dfile=$TRAVIS_DIR/hg-pd-grpc-3.0.0.jar -DgroupId=com.baidu.hugegraph -DartifactId=hg-pd-grpc -Dversion=3.0.0 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/hg-pd-grpc-pom.xml
          mvn install:install-file -Dfile=$TRAVIS_DIR/hg-store-client-3.0.0.jar -DgroupId=com.baidu.hugegraph -DartifactId=hg-store-client -Dversion=3.0.0 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/hg-store-client-pom.xml
          mvn install:install-file -Dfile=$TRAVIS_DIR/hg-store-grpc-3.0.0.jar -DgroupId=com.baidu.hugegraph -DartifactId=hg-store-grpc -Dversion=3.0.0 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/hg-store-grpc-pom.xml
          mvn install:install-file -Dfile=$TRAVIS_DIR/hg-store-term-3.0.0.jar -DgroupId=com.baidu.hugegraph -DartifactId=hg-store-term -Dversion=3.0.0 -Dpackaging=jar -DpomFile=$TRAVIS_DIR/hg-store-term-pom.xml

      - name: Build images
        env:
          TRAVIS_DIR: computer-dist/src/assembly/travis
        run: $TRAVIS_DIR/build-images.sh ${{ github.event.inputs.framework_image_url }} ${{ github.event.inputs.algorithm_image_url }} ${{ github.event.inputs.operator_image_url }}

      - name: Docker images
        run: docker images

      - name: Save image
        run: |
          mkdir artifacts
          chmod -R 777 ./artifacts
          docker save -o ./artifacts/hugegraph-computer-framework.tar ${{ github.event.inputs.framework_image_url }}
          docker save -o ./artifacts/hugegraph-computer-algorithm.tar ${{ github.event.inputs.algorithm_image_url }}
          docker save -o ./artifacts/hugegraph-computer-operator.tar ${{ github.event.inputs.operator_image_url }}

      - name: Upload github release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "./artifacts/*"
          tags: true
          draft: false
          overwrite: true
          tag_name: ${{ github.event.inputs.release_tag }}
